//! Core Bitcoin and protocol types for SCP.
//!
//! This module provides type-safe wrappers around Bitcoin primitives
//! and protocol-specific identifiers.

use bitcoin::hashes::{sha256, Hash};
use serde::{Deserialize, Serialize};
use std::fmt;

/// A satoshi amount (1 BTC = 100,000,000 satoshis).
///
/// This is a simple wrapper to prevent confusion between different units.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct Satoshi(pub u64);

impl Satoshi {
    /// Zero satoshis.
    pub const ZERO: Self = Self(0);

    /// One Bitcoin in satoshis.
    pub const ONE_BTC: Self = Self(100_000_000);

    /// Create from satoshis.
    pub fn from_sat(sats: u64) -> Self {
        Self(sats)
    }

    /// Create from BTC (will truncate fractional satoshis).
    pub fn from_btc(btc: f64) -> Self {
        Self((btc * 100_000_000.0) as u64)
    }

    /// Get the raw satoshi value.
    pub fn as_sat(&self) -> u64 {
        self.0
    }

    /// Convert to BTC as floating point.
    pub fn as_btc(&self) -> f64 {
        self.0 as f64 / 100_000_000.0
    }

    /// Checked addition.
    pub fn checked_add(self, other: Self) -> Option<Self> {
        self.0.checked_add(other.0).map(Self)
    }

    /// Checked subtraction.
    pub fn checked_sub(self, other: Self) -> Option<Self> {
        self.0.checked_sub(other.0).map(Self)
    }
}

impl fmt::Display for Satoshi {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} sats", self.0)
    }
}

impl std::ops::Add for Satoshi {
    type Output = Self;
    fn add(self, rhs: Self) -> Self::Output {
        Self(self.0 + rhs.0)
    }
}

impl std::ops::Sub for Satoshi {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self::Output {
        Self(self.0 - rhs.0)
    }
}

/// A unique identifier for a DLC contract.
///
/// Generated by hashing the contract parameters.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ContractId([u8; 32]);

impl ContractId {
    /// Create a new contract ID from raw bytes.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Generate a contract ID from arbitrary data.
    pub fn from_data(data: &[u8]) -> Self {
        let hash = sha256::Hash::hash(data);
        Self(hash.to_byte_array())
    }

    /// Get the raw bytes.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// Convert to hex string.
    pub fn to_hex(&self) -> String {
        hex::encode(self.0)
    }
}

impl fmt::Display for ContractId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", &self.to_hex()[..16]) // Show first 16 chars
    }
}

/// A wrapper around secp256k1 public key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PublicKey(#[serde(with = "pubkey_serde")] pub secp256k1::PublicKey);

impl PublicKey {
    /// Create from a secp256k1 public key.
    pub fn new(key: secp256k1::PublicKey) -> Self {
        Self(key)
    }

    /// Get the inner secp256k1 key.
    pub fn inner(&self) -> &secp256k1::PublicKey {
        &self.0
    }
}

impl fmt::Display for PublicKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::str::FromStr for PublicKey {
    type Err = secp256k1::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let key = secp256k1::PublicKey::from_str(s)?;
        Ok(Self(key))
    }
}

mod pubkey_serde {
    use serde::{self, Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(key: &secp256k1::PublicKey, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&key.to_string())
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<secp256k1::PublicKey, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        s.parse().map_err(serde::de::Error::custom)
    }
}

/// Oracle information for DLC attestation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OracleInfo {
    /// The oracle's public key.
    pub public_key: PublicKey,
    /// Human-readable name of the oracle.
    pub name: String,
    /// URL endpoint for fetching attestations.
    pub endpoint: Option<String>,
}

/// Timestamp in Unix seconds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Timestamp(pub u64);

impl Timestamp {
    /// Current time.
    pub fn now() -> Self {
        use std::time::{SystemTime, UNIX_EPOCH};
        let secs = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        Self(secs)
    }

    /// Create from Unix timestamp.
    pub fn from_unix(secs: u64) -> Self {
        Self(secs)
    }

    /// Check if this timestamp is in the past.
    pub fn is_past(&self) -> bool {
        self.0 < Self::now().0
    }
}

/// Hex encoding utilities (simple implementation).
mod hex {
    pub fn encode(bytes: impl AsRef<[u8]>) -> String {
        bytes
            .as_ref()
            .iter()
            .map(|b| format!("{:02x}", b))
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_satoshi_conversion() {
        let one_btc = Satoshi::from_btc(1.0);
        assert_eq!(one_btc.as_sat(), 100_000_000);
        assert_eq!(one_btc.as_btc(), 1.0);

        let half_btc = Satoshi::from_sat(50_000_000);
        assert_eq!(half_btc.as_btc(), 0.5);
    }

    #[test]
    fn test_satoshi_arithmetic() {
        let a = Satoshi::from_sat(100);
        let b = Satoshi::from_sat(50);
        assert_eq!((a + b).as_sat(), 150);
        assert_eq!((a - b).as_sat(), 50);
    }

    #[test]
    fn test_contract_id_generation() {
        let id1 = ContractId::from_data(b"test contract 1");
        let id2 = ContractId::from_data(b"test contract 2");
        assert_ne!(id1, id2);

        // Same data = same ID
        let id1_again = ContractId::from_data(b"test contract 1");
        assert_eq!(id1, id1_again);
    }
}

/// A wrapper around a 32-byte scalar value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Scalar(pub [u8; 32]);

impl Scalar {
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }
}
